### ISSUE TITLE
Typo in the dockerfile

### ISSUE THREAD

**Issue by fcastello** [mmcc/runscope-agent-docker#1]
Hey I found a typo in your dockerfile.
rm -rf /var/lib/apt/lists/\* /tmp/\* /var/tmp/\* runscop-radar.zip 
shouldn't be
rm -rf /var/lib/apt/lists/\* /tmp/\* /var/tmp/\* runscope-radar.zip

Can you fix it and rebuild it in dockerhub?

**Comment by mmcc** [comment]
Ah nice catch! If you'd like you can submit a PR to fix this I'll wait on it, otherwise I can push the fixated today.

**Comment by mmcc** [comment]
Just pushed a change, which triggered a build on docker hub. Should be done shortly.

**Comment by fcastello** [comment]
Great .thanks I will choir from dockerhub!
